homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/New_York

default_config:

input_select: !include input_select.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
homekit: !include homekit.yaml
device_tracker: !include device_tracker.yaml
