default_config:

homeassistant: !include homeassistant.yaml

automation brewery: !include automations/brewery.yaml
automation kitchen: !include automations/kitchen.yaml
automation guest_bedroom: !include automations/guest_bedroom.yaml
automation living_room: !include automations/living_room.yaml
automation office: !include automations/office.yaml
automation presence: !include automations/presence.yaml

climate: !include climate.yaml

device_tracker: !include device_tracker.yaml

homekit: !include homekit.yaml

input_select: !include input_select.yaml

meross_cloud: !include meross_cloud.yaml

mqtt: !include mqtt.yaml

rest_command: !include rest_command.yaml

scene: !include scenes.yaml

sensor tilt: !include sensors/tilt.yaml

zone: !include zones.yaml

zwave: !include zwave.yaml
