homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/New_York

default_config:

input_select: !include input_select.yaml

automation kitchen: !include automations/kitchen.yaml
automation guest_bedroom: !include automations/guest_bedroom.yaml
automation living_room: !include automations/living_room.yaml
automation office: !include automations/office.yaml
automation presence: !include automations/presence.yaml

scene: !include scenes.yaml
zone: !include zones.yaml
homekit: !include homekit.yaml
device_tracker: !include device_tracker.yaml
zwave: !include zwave.yaml

meross_cloud:
  username: !secret meross_username
  password: !secret meross_password

mqtt: !include mqtt.yaml
