- alias: Living Room Button Turn On Lights
  description: ""
  trigger:
    - platform: device
      device_id: a431db9b28504b03af40c98b74ac1127
      domain: zha
      type: remote_button_short_press
      subtype: remote_button_short_press
  condition:
    - condition: state
      entity_id: input_select.living_room_scene
      state: none
  action:
    - service: input_select.select_option
      entity_id: input_select.living_room_scene
      data:
        option: all

- alias: Living Room Button Turn Off Lights
  description: ""
  trigger:
    - platform: device
      device_id: a431db9b28504b03af40c98b74ac1127
      domain: zha
      type: remote_button_short_press
      subtype: remote_button_short_press
  condition:
    - condition: template
      value_template: "{{ not is_state('input_select.living_room_scene', 'none') }}"
  action:
    - service: input_select.select_option
      entity_id: input_select.living_room_scene
      data:
        option: none

- alias: Living Room Button Cycle Scenes
  description: ""
  trigger:
    - platform: device
      device_id: a431db9b28504b03af40c98b74ac1127
      domain: zha
      type: remote_button_double_press
      subtype: remote_button_double_press
  condition: []
  action:
    - service: input_select.select_next
      data:
        entity_id: input_select.living_room_scene

- alias: Select Scene Living Room All Lights
  description: ""
  trigger:
    - platform: state
      entity_id: input_select.living_room_scene
      to: all
  condition: []
  action:
    - scene: scene.living_room_all_lights

- alias: Select Scene Living Room No Lights
  description: ""
  trigger:
    - platform: state
      entity_id: input_select.living_room_scene
      to: none
  condition: []
  action:
    - scene: scene.living_room_no_lights

- alias: Select Scene Living Room Tower Lamp Only
  description: ""
  trigger:
    - platform: state
      entity_id: input_select.living_room_scene
      to: tower
  condition: []
  action:
    - scene: scene.living_room_only_tower_lamp

- alias: Select Scene Living Room Ampersand Light Only
  description: ""
  trigger:
    - platform: state
      entity_id: input_select.living_room_scene
      to: ampersand
  condition: []
  action:
    - scene: scene.living_room_only_ampersand_light
