- alias: Living Room Button Turn On Lights
  description: ""
  trigger:
    - platform: device
      device_id: a431db9b28504b03af40c98b74ac1127
      domain: zha
      type: remote_button_short_press
      subtype: remote_button_short_press
  condition:
    - condition: state
      entity_id: group.living_room_lamps
      state: "off"
  action:
    - service: homeassistant.turn_on
      entity_id: group.living_room_lamps

- alias: Living Room Button Turn Off Lights
  description: ""
  trigger:
    - platform: device
      device_id: a431db9b28504b03af40c98b74ac1127
      domain: zha
      type: remote_button_short_press
      subtype: remote_button_short_press
  condition:
    - condition: state
      entity_id: group.living_room_lamps
      state: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: group.living_room_lamps
