- alias: Office Button Toggle Lights
  description: ""
  trigger:
    - platform: device
      device_id: b632a727fe2c41569d5cc83698124212
      domain: zha
      type: remote_button_short_press
      subtype: remote_button_short_press
  action:
    - service: light.toggle
      entity_id: group.office_lamps
